### ISSUE TITLE
polysemy-plugin version bump

### ISSUE THREAD

**Issue by funketh** [adamConnerSax/polysemy-Extra#5]
polysemy-plugin 0.4 is required for ghc 9 and this package already works fine if the bounds are ignored

**Comment by adamConnerSax** [comment]
Thanks!  Sorry it took me a bit to notice.  
Bumped polysemy-plugin upper bound (https://github.com/adamConnerSax/polysemy-Extra/commit/5f3b13d6a3874d5e3a5993b6dd7c1279bde4be7e) and released on hackage.
Actually looks like last release is in that commit too. Bad form on my part. Sigh.
